"""changed nullabilty

Revision ID: b7ce841a0e78
Revises: 821f0bb40edc
Create Date: 2022-12-27 19:42:26.623876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ce841a0e78'
down_revision = '821f0bb40edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_report', schema=None) as batch_op:
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('individual_report', schema=None) as batch_op:
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('propsal', schema=None) as batch_op:
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('propsal', schema=None) as batch_op:
        batch_op.alter_column('gId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('individual_report', schema=None) as batch_op:
        batch_op.alter_column('sId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('group_report', schema=None) as batch_op:
        batch_op.alter_column('gId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
