"""empty message

Revision ID: c99dc9f01898
Revises: 
Create Date: 2022-12-29 16:28:20.250385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99dc9f01898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('publish', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.Boolean(), nullable=True),
    sa.Column('authorize', sa.Boolean(), nullable=True),
    sa.Column('studentCount', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_member_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_faculty_member_username'), ['username'], unique=True)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_username'), ['username'], unique=True)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fId', sa.Integer(), nullable=True),
    sa.Column('sId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fId'], ['faculty_member.id'], ),
    sa.ForeignKeyConstraint(['sId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fId', sa.Integer(), nullable=True),
    sa.Column('gId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fId'], ['faculty_member.id'], ),
    sa.ForeignKeyConstraint(['gId'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propsal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.String(length=2064), nullable=False),
    sa.Column('fId', sa.Integer(), nullable=True),
    sa.Column('gId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fId'], ['faculty_member.id'], ),
    sa.ForeignKeyConstraint(['gId'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propsal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propsal_desc'), ['desc'], unique=True)
        batch_op.create_index(batch_op.f('ix_propsal_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propsal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propsal_title'))
        batch_op.drop_index(batch_op.f('ix_propsal_desc'))

    op.drop_table('propsal')
    op.drop_table('group_report')
    op.drop_table('individual_report')
    op.drop_table('group')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_username'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('faculty_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_member_username'))
        batch_op.drop_index(batch_op.f('ix_faculty_member_email'))

    op.drop_table('faculty_member')
    # ### end Alembic commands ###
